## Numpy Array Operations

In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing :", arr[2:7])
print("With step: ", arr[1:8:2]) #last one is step
print("Negative indexing:", arr[-3])

Basic Slicing : [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing: 8


In [11]:
arr_2d= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific Element: ",arr_2d[1,2])
print("Entire Row: ",arr_2d[1])
print("Entire Column: ",arr_2d[:,2])


Specific Element:  6
Entire Row:  [4 5 6]
Entire Column:  [3 6 9]


### Sorting

In [18]:
unsorted = np.array([4,1,3,5,7,6,9,2])
print("Unsorted array:",unsorted)
print("Sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[4,8],[6,3]])
print("Sorted 2D Array by Column is :\n", np.sort(arr_2d_unsorted, axis =0)) # Sorted by Top to Bottom

print("Sorted 2D Array by Row is :\n", np.sort(arr_2d_unsorted, axis =1)) # Sorted by Left to Right

Unsorted array: [4 1 3 5 7 6 9 2]
Sorted Array: [1 2 3 4 5 6 7 9]
Sorted 2D Array by Column is :
 [[3 1]
 [4 3]
 [6 8]]
Sorted 2D Array by Row is :
 [[1 3]
 [4 8]
 [3 6]]


### Filtering

In [28]:
num= np.array([1,2,3,4,5,6,7,8,9,10])
even_nmm =num[num % 2 == 0]
print("Ëven numbers =",even_nmm )

Ëven numbers = [ 2  4  6  8 10]


### Filter with mask

In [22]:
mask = num > 5
print("Number greater than 5 is", num[mask])

Number greater than 5 is [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [31]:
indices = [0,2,4]
print(num[indices])

where_result= np.where(num>5)  
print(where_result)  # here, "where_result" has stored indices of array satisfying the condition
print("NP where",num[where_result]) # This is exactly like masking.


[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [34]:
condition_array=np.where(num > 5, num * 2, num)

print(condition_array)

condition_array=np.where(num > 5, "True", "false")

print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'True' 'True' 'True' 'True'
 'True']


### Add or Remove data

In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1,arr2))
print(combined_arr)

[1 2 3 4 5 6]


### Array Compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("compability shapes:", a.shape == b.shape)
print("compability shapes:", a.shape == c.shape)


original =np.array([[1,2],[3,4]])
print("\nOriginal Array:\n",original)

new_row =np.array([[5,6]])
with_new_row =np.vstack((original, new_row)) # vstack always adds the row
print("\nwith new Row:\n",with_new_row)

new_col = np.array([[7],[8]])
print("\nOriginal Array:\n",original)

with_new_col = np.hstack((original, new_col)) # hstack always adds the Column
print("\nwith new Column:\n",with_new_col)




compability shapes: True
compability shapes: False

Original Array:
 [[1 2]
 [3 4]]

with new Row:
 [[1 2]
 [3 4]
 [5 6]]

Original Array:
 [[1 2]
 [3 4]]

with new Column:
 [[1 2 7]
 [3 4 8]]


In [56]:
arr =np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr, 2) # it will delete the exact 2 position element.
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5 6 7 8 9]
