## Numpy array and Basics

In [3]:
import numpy as np

## Creating array with list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1d array:", arr_1d)

arr_2d = np.array([[2,3,4,5,6],[7,8,9,0,1]])

print("2d array:",arr_2d)

1d array: [1 2 3 4 5]
2d array: [[2 3 4 5 6]
 [7 8 9 0 1]]


### List vs Numpy Array

In [ ]:
py_list = [1,2,3,4]
print("Python list multiplication:", py_list * 2)

Python list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
np_array = np.array([1,2,3,4]) #Element wise multiplication 
print("Python list multiplication:", np_array * 2)

Python list multiplication: [2 4 6 8]


In [14]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time", time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n Numpy operation time", time.time() - start)


 List operation time 0.008405685424804688

 Numpy operation time 0.0006594657897949219


### Creating array from Scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zeros array =\n ",zeros)

ones = np.ones((3,4))
print("Ones array =\n ",ones)

full = np.full((2,2), 7)
print("Full array =\n ",full)

random = np.random.random((2,3))
print("Random array =\n ",random)

sequence = np.arange(0,10,2) # Ranges from 0 to 9 with step =2.
print("Sequence array =\n ",sequence)


Zeros array =
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array =
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array =
  [[7 7]
 [7 7]]
Random array =
  [[0.45003242 0.28674597 0.48712161]
 [0.17971126 0.21979777 0.05058078]]
Sequence array =
  [0 2 4 6 8]


### Vector, Matrices and Tensor

In [26]:
vector = np.array([1,2,3])
print("Vector:",vector)

matrices = np.array([[1,2,3],
                    [4,5,6]])
print("\nMatrices:\n", matrices)

tensor = np.array([[[1,2], [3,4]],
                  [[5,6],[7,8]]])

print("\nTensor:",tensor)

Vector: [1 2 3]

Matrices:
 [[1 2 3]
 [4 5 6]]

Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [30]:
arr = np.array([[1,2,3],
               [4,5,6]]) #Numpy array's optimised as they store similar data of types as we can do arr = np.array([[1,2,3],
               # [4,5,True]]) as well.
print("Shape of array :", arr.shape) # Gives rows and column
print("Dimension:",arr.ndim) # Gives Dimension
print("Size:",arr.size) # Gives Size(Total number of elements)
print("Dtype:",arr.dtype) # Gives Datatype

Shape of array : (2, 3)
Dimension: 2
Size: 6
Dtype: int64


### Array Reshaping

In [31]:
arr = np.arange(12)
print("Original Array :", arr)

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
reshaped = arr.reshape((3,4)) # Convert into 3*4 matrix
print("\n Reshaped array:", reshaped)

flattened= reshaped.flatten()
print("\n flattened array:",flattened) #Convert into flat array in one row.

raveled = reshaped.ravel() # It returns the view not copy.
print("\n Raveled array :", raveled) 

transpose = reshaped.T
print("\n Transpose:",transpose) # It returns the transpose of the matrix.


 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
